#!/usr/bin/env python3
"""
generate.py — one-shot generator for every secret the Router needs.

Produces:
  - SERVER_SECRET          (hex)   — HMAC key, derives mailbox_id from a pubkey
  - ROUTER_SHARED_SECRET   (hex)   — optional, gates /status + admin endpoints
  - ROUTER_SIGNING_KEY     (base64 PKCS8) — Ed25519 PRIVATE key, signs
                                            capabilities + routing tables
  - ROUTER_SIGNING_PUBLIC  (hex)   — the PUBLIC half of the same keypair;
                                     safe to commit/hardcode, every shard
                                     needs this exact value to verify things

Nothing here ever needs to be shared with a shard operator except
ROUTER_SIGNING_PUBLIC, which is public by design. Shards generate their own,
separate self-registration identity automatically on first boot — this
script has nothing to do with that.

Usage:
    python3 generate.py                # human-readable output
    python3 generate.py --dev-vars     # also write a ready-to-use .dev.vars
    python3 generate.py --json         # machine-readable JSON on stdout

Requires: pip install cryptography --break-system-packages
"""

import argparse
import base64
import json
import secrets
import sys

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
except ImportError:
    print(
        "Missing dependency. Install it first:\n"
        "  pip install cryptography --break-system-packages\n",
        file=sys.stderr,
    )
    sys.exit(1)


def generate_hex_secret(num_bytes: int = 32) -> str:
    return secrets.token_hex(num_bytes)


def generate_signing_keypair() -> dict:
    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()

    private_pkcs8_der = private_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_raw = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )

    return {
        "private_pkcs8_base64": base64.b64encode(private_pkcs8_der).decode("ascii"),
        "public_hex": public_raw.hex(),
    }


def generate_all() -> dict:
    keypair = generate_signing_keypair()
    return {
        "SERVER_SECRET": generate_hex_secret(32),
        "ROUTER_SHARED_SECRET": generate_hex_secret(32),
        "ROUTER_SIGNING_KEY": keypair["private_pkcs8_base64"],
        "ROUTER_SIGNING_PUBLIC": keypair["public_hex"],
    }


def print_human(values: dict) -> None:
    print("=" * 78)
    print("  Router secrets — generated fresh, never reuse across environments")
    print("=" * 78)
    print()
    print("SECRETS (set these with `wrangler secret put <NAME>`, never commit):")
    print()
    for name in ("SERVER_SECRET", "ROUTER_SIGNING_KEY", "ROUTER_SHARED_SECRET"):
        print(f"  {name}")
        print(f"    {values[name]}")
        print()
    print("-" * 78)
    print("PUBLIC VALUE (safe to commit to wrangler.toml [vars], and to hand to")
    print("shard operators so their worker.js can verify your signatures):")
    print()
    print("  ROUTER_SIGNING_PUBLIC")
    print(f"    {values['ROUTER_SIGNING_PUBLIC']}")
    print()
    print("-" * 78)
    print("Quick setup:")
    print()
    print("  echo -n '" + values["SERVER_SECRET"] + "' | wrangler secret put SERVER_SECRET")
    print("  echo -n '" + values["ROUTER_SIGNING_KEY"] + "' | wrangler secret put ROUTER_SIGNING_KEY")
    print("  echo -n '" + values["ROUTER_SHARED_SECRET"] + "' | wrangler secret put ROUTER_SHARED_SECRET")
    print()
    print("  # then in wrangler.toml [vars]:")
    print(f'  ROUTER_SIGNING_PUBLIC = "{values["ROUTER_SIGNING_PUBLIC"]}"')
    print()


def write_dev_vars(values: dict, path: str = ".dev.vars") -> None:
    lines = [
        "# Generated by generate.py — local `wrangler dev` only, NEVER commit this file.",
        f'SERVER_SECRET="{values["SERVER_SECRET"]}"',
        f'ROUTER_SHARED_SECRET="{values["ROUTER_SHARED_SECRET"]}"',
        f'ROUTER_SIGNING_KEY="{values["ROUTER_SIGNING_KEY"]}"',
        f'ROUTER_SIGNING_PUBLIC="{values["ROUTER_SIGNING_PUBLIC"]}"',
        "PRIOR_SHARD_COUNTS='[]'",
        "ROUTING_TABLE_VERSION=1",
        "SHARD_URLS='[]'",
        "REPLICATION_FACTOR=1",
        "SHARD_POW_DIFFICULTY_BITS=8",
        "MAX_REGISTERED_SHARDS=200",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dev-vars", action="store_true", help="also write a .dev.vars file in the current directory")
    parser.add_argument("--json", action="store_true", help="print machine-readable JSON instead of the human summary")
    parser.add_argument("--out", default=".dev.vars", help="path for --dev-vars output (default: ./.dev.vars)")
    args = parser.parse_args()

    values = generate_all()

    if args.json:
        print(json.dumps(values, indent=2))
    else:
        print_human(values)

    if args.dev_vars:
        write_dev_vars(values, args.out)


if __name__ == "__main__":
    main()